spring.application.name=contact-backend

server.port=${PORT:8080}

# Email Configuration
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

app.mail.to=${MAIL_TO:${MAIL_USERNAME}}
app.mail.from=${MAIL_FROM:${MAIL_USERNAME}}

# CORS Configuration
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}
